# Generated by Django 5.2.4 on 2025-08-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_text', models.CharField()),
                ('tags', models.CharField()),
                ('creation_datetime', models.DateTimeField()),
                ('last_edit_datetime', models.DateTimeField()),
            ],
        ),
    ]
