# Generated by Django 5.2.4 on 2025-08-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_entry_entry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='last_edit_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
