# Generated by Django 5.2.4 on 2025-08-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_alter_entry_last_edit_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='last_edit_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
