# Generated by Django 5.2.4 on 2025-08-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_entry_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=models.CharField(blank=True, null=True),
        ),
    ]
