# Generated by Django 5.2.4 on 2025-08-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_alter_entry_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
    ]
