# Generated by Django 5.2.4 on 2025-08-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_delete_journaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_text_wordcount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
