# Generated by Django 5.2.13 on 2026-08-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_entry_entry_text_wordcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='tags',
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_title',
            field=models.CharField(default='Untitled', max_length=64),
        ),
    ]
